name: Build "turnip"

on:
  workflow_dispatch:
  schedule:
  - cron: "20 5 1,15 * *"

jobs:
  start_building_turnip:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo apt update
        sudo apt build-dep mesa -y
    
    - name: Execute build script
      run: bash ./turnip_builder.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Upload meson and ninja logs for debugging
        path: |
          turnip_workdir/ninja_log
          turnip_workdir/mesa/build-android-aarch64/meson-logs/meson-log.txt
    
    - id: versions
      name: "Get release info"
      run: |
        echo "name=$(cat turnip_workdir/release)" >> "$GITHUB_OUTPUT"
        echo "tag=$(cat turnip_workdir/tag)" >> "$GITHUB_OUTPUT"
        echo "filename=$(cat turnip_workdir/filename)" >> "$GITHUB_OUTPUT"
        echo "patched=$(cat turnip_workdir/patched)" >> "$GITHUB_OUTPUT"

      
    - name: Release "turnip" with patched
      if: ${{ contains(steps.versions.outputs.patched, 'true') }}
      uses: softprops/action-gh-release@v1
      with:
        body_path: turnip_workdir/description
        name: ${{ steps.versions.outputs.name }}
        tag_name: ${{ steps.versions.outputs.tag }}
        files: |
           turnip_workdir/${{ steps.versions.outputs.filename }}.zip
           turnip_workdir/${{ steps.versions.outputs.filename }}_patched.zip

    - name: Release "turnip" without patched
      if: ${{ contains(steps.versions.outputs.patched, 'false') }}
      uses: softprops/action-gh-release@v1
      with:
        body_path: turnip_workdir/description
        name: ${{ steps.versions.outputs.name }}
        tag_name: ${{ steps.versions.outputs.tag }}
        files: |
           "turnip_workdir/${{ steps.versions.outputs.filename }}.zip"
